# Generated by Django 4.2.7 on 2023-11-20 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filme',
            old_name='thum',
            new_name='thumb',
        ),
    ]
